#
# Copyright 2020, Fernando Lemes da Silva
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: '2'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=sample-application
      - MYSQL_USER=user
      - MYSQL_PASSWORD=abc123
  application-1:
    container_name: application-1
    image: application
    build:
      context: .
      dockerfile: Dockerfile-application
    environment:
      - MYSQL_DATABASE=sample-application
      - MYSQL_USER=user
      - MYSQL_PASSWORD=abc123
    links:
      - mysql
  application-2:
    container_name: application-2
    image: application
    build:
      context: .
      dockerfile: Dockerfile-application
    environment:
      - MYSQL_DATABASE=sample-application
      - MYSQL_USER=user
      - MYSQL_PASSWORD=abc123
    links:
      - mysql
  application-3:
    container_name: application-3
    image: application
    build:
      context: .
      dockerfile: Dockerfile-application
    environment:
      - MYSQL_DATABASE=sample-application
      - MYSQL_USER=user
      - MYSQL_PASSWORD=abc123
    links:
      - mysql
  haproxy:
    container_name: haproxy
    image: haproxy
    build:
      context: .
      dockerfile: Dockerfile-haproxy
    ports:
      - "8080:8080"
    links:
      - application-1
      - application-2
      - application-3
  jmeter:
    container_name: jmeter
    image: jmeter
    build:
      context: .
      dockerfile: Dockerfile-jmeter
    links:
      - haproxy
    volumes:
      - ./jmeter_results:/results
